apiVersion: skaffold/v2beta8
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: stephengrider/multi-client
      context: client
      docker:
        dockerfild: Dockerfile.dev
      sync:
        "**.*.js": .
        "**.*.css": .
        "**.*.html": .

deploy:
  kubectl:
    manifests:
      - k8s/client.yaml
